### PR TITLE
added pom.xml to make project structure into maven 

### PR DESCRIPTION
**Pull request by koolgreg2009**
added pom.xml to make project structure into maven 
also fixed some bits

### CODE REVIEW

**Comment by koolgreg2009** [comment]
i added pomxml in #28  [7d0f8be](https://github.com/koolgreg2009/group8csc207/pull/28/commits/7d0f8beabe50744a6a145088344ce2f19d2c328f)

**Comment by jennyyay** [comment]
don't need maven sorry :(

**Comment by jennyyay** [comment]
actually sike we can if we want to

**Comment by jennyyay** [comment]
ok sike x2 can u pull from mine and then edit the user information sorry :(( or is there a way for u to rebase it? cause the pom doesnt work so i had to add in a new version-- i dont want to merge this pull req into the repo

**Pull request closed without merging**
